config/routes.rb
Phototagger::Application.routes.draw do
  root :to => 'session#new'
  resources :photos, :only => [:create, :show, :destroy, :index] do
    resources :tags, :only => [:create]
  end
  resources :session, :only => [:new, :create, :destroy]
  resources :users, :only => [:show] do
    resources :photos, :only => [:index]
  end

  get "friends", :controller => :users
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :user_id, :friend_id

  belongs_to :friend, :class_name => "User"
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :url, :user_id
  belongs_to :user
  has_many :tags

  validates :url, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :photo_id, :friend_id, :xco, :yco

  belongs_to :photo
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  require "bcrypt"
  attr_accessible :username, :password

  has_many :photos

  has_many :friendships
  has_many :friends, :through => :friendships

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def assign_new_token!
    self.token = SecureRandom.urlsafe_base64(24)
    self.save!

    return self.token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :find_current_user

  def current_user
    @current_user ||= User.find_by_token(session[:token])
  end

  def find_current_user
    if session[:token]
      current_user
    else
      @current_user = nil
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    if params[:user_id]

      @photos = User.where(params[:user_id]).includes(:tags)
    else
      @photos = current_user.photos.includes(:tags)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos.to_json(include: [:tags]) }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])
    @photo.user_id = @current_user.id

    respond_to do |format|
      if @photo.save
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.json { render json: @photo }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    user = User.find_by_username(params[:username])
    if user.verify_password(params[:password])
      session[:token] = user.assign_new_token!
      redirect_to user_photos_path(user)
    else
      render :json => "Go away Hacker"
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_username(params[:username])
    if user.verify_password(params[:password])
      session[:token] = user.assign_new_token!
    else
      render :json => "Go away Hacker"
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @tag = Tag.new(params[:tag])
    p @tag
    @tag.photo_id = params[:photo_id]
    if @tag.save
      render json: @tag
    else
      render json: @tag.errors
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_to_login


  def show
    render json: @current_user
  end

  def redirect_to_login
    unless @current_user
      redirect_to new_session_path
    end
  end

  def friends
    render json: @current_user.friends
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phototagger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="span12">
		<%= yield %>
	</div>


</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<div id="photos_window">
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/session/new.html.erb
<form action="<%= session_index_path %>" method="post" accept-charset="utf-8">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" id="authenticity_token">
	<label for="Username">Username</label><input type="text" name="username" value="" id="Username">
	<label for="Password">Password</label><input type="password" name="password" value="" id="Password">

	<p><input type="submit" value="Continue &rarr;"></p>
</form>